USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS FOODINTEL_WH
  WAREHOUSE_SIZE = 'XSMALL' -- extra small
  AUTO_SUSPEND   = 60 -- so the trial credits last
  AUTO_RESUME    = TRUE
  INITIALLY_SUSPENDED = TRUE;

-- Database + medallion schemas.
CREATE DATABASE IF NOT EXISTS FOODINTEL;
CREATE SCHEMA  IF NOT EXISTS FOODINTEL.BRONZE;    -- Iceberg tables Spark wrote (dbt sources)
CREATE SCHEMA  IF NOT EXISTS FOODINTEL.RAW;       -- only used by the COPY fallback path
CREATE SCHEMA  IF NOT EXISTS FOODINTEL.STAGING;   -- cleaned / conformed (dbt)
CREATE SCHEMA  IF NOT EXISTS FOODINTEL.MARTS;     -- Gold, Iceberg (dbt)
CREATE SCHEMA  IF NOT EXISTS FOODINTEL.SNAPSHOTS; -- SCD2 history (dbt)
CREATE SCHEMA  IF NOT EXISTS FOODINTEL.AI;        -- LLM-enriched tables (Groq jobs)

-- For airflow/dpt 
CREATE ROLE IF NOT EXISTS DBT_ROLE;
GRANT USAGE   ON WAREHOUSE FOODINTEL_WH TO ROLE DBT_ROLE;
GRANT OPERATE ON WAREHOUSE FOODINTEL_WH TO ROLE DBT_ROLE;
GRANT ALL     ON DATABASE  FOODINTEL    TO ROLE DBT_ROLE;
GRANT ALL     ON ALL SCHEMAS IN DATABASE FOODINTEL TO ROLE DBT_ROLE;
GRANT ALL     ON FUTURE SCHEMAS IN DATABASE FOODINTEL TO ROLE DBT_ROLE;
GRANT ALL     ON FUTURE TABLES IN DATABASE FOODINTEL TO ROLE DBT_ROLE;
GRANT ALL     ON FUTURE VIEWS  IN DATABASE FOODINTEL TO ROLE DBT_ROLE;

-- Let our login use the role 
SET my_user = CURRENT_USER();
GRANT ROLE DBT_ROLE TO USER IDENTIFIER($my_user);

SELECT 'setup complete' AS status;