 USE ROLE ACCOUNTADMIN;

 CREATE OR REPLACE STORAGE INTEGRATION FOODINTEL_S3_INT
    TYPE = EXTERNAL_STAGE
    STORAGE_PROVIDER = 'S3'
    ENABLED = TRUE
    STORAGE_AWS_ROLE_ARN='arn:aws:iam::358115276900:role/foodIntel-snowflake-s3-role'
    STORAGE_ALLOWED_LOCATIONS=('s3://foodintel-pipeline-dev/');
    
    GRANT USAGE ON INTEGRATION FOODINTEL_S3_INT TO ROLE DBT_ROLE;

    DESCRIBE INTEGRATION FOODINTEL_S3_INT; -- give all information related to description