USE ROLE ACCOUNTADMIN;
USE DATABASE FOODINTEL;
USE SCHEMA RAW;

CREATE OR REPLACE FILE FORMAT FOODINTEL.RAW.CSV_FMT
    TYPE="CSV"
    COMPRESSION='AUTO'
    FIELD_DELIMITER=','
    FIELD_OPTIONALLY_ENCLOSED_BY='"'
    SKIP_HEADER=1
    EMPTY_FIELD_AS_NULL=TRUE
    NULL_IF=(' ', '\\N', 'NULL')
    TRIM_SPACE=FALSE
    ERROR_ON_COLUMN_COUNT_MISMATCH=FALSE; // directly load error data , we will handle it on transform layer

CREATE OR REPLACE STAGE FOODINTEL.RAW.FOODINTEL_RAW_STAGE
    STORAGE_INTEGRATION = FOODINTEL_S3_INT
    URL='S3://foodintel-pipeline-dev/raw/'
    FILE_FORMAT = FOODINTEL.RAW.CSV_FMT;

LIST @FOODINTEL.RAW.FOODINTEL_RAW_STAGE;