USE ROLE ACCOUNTADMIN;
USE DATABASE FOODINTEL;
USE SCHEMA RAW;
USE WAREHOUSE FOODINTEL_WH;

-- Dimesion
COPY INTO RAW.restaurants FROM @FOODINTEL_RAW_STAGE/restaurants ON_ERROR=CONTINUE;
COPY INTO RAW.users       FROM @FOODINTEL_RAW_STAGE/users/        ON_ERROR = 'CONTINUE';
COPY INTO RAW.food        FROM @FOODINTEL_RAW_STAGE/food/         ON_ERROR = 'CONTINUE';
COPY INTO RAW.menu        FROM @FOODINTEL_RAW_STAGE/menu/         ON_ERROR = 'CONTINUE';

-- Facts 
COPY INTO RAW.orders      FROM @FOODINTEL_RAW_STAGE/orders/       ON_ERROR = 'ABORT_STATEMENT';
COPY INTO RAW.order_items FROM @FOODINTEL_RAW_STAGE/order_items/  ON_ERROR = 'ABORT_STATEMENT';
COPY INTO RAW.reviews     FROM @FOODINTEL_RAW_STAGE/reviews/      ON_ERROR = 'ABORT_STATEMENT';

-- Sanity check.
-- SELECT * FROM RAW.restaurants LIMIT 10;
SELECT 'restaurants' t, COUNT(*) n FROM RAW.restaurants
UNION ALL SELECT 'users',COUNT(*) FROM RAW.users
UNION ALL SELECT 'food',COUNT(*) FROM RAW.food
UNION ALL SELECT 'menu',COUNT(*) FROM RAW.menu
UNION ALL SELECT 'orders',COUNT(*) FROM RAW.orders
UNION ALL SELECT 'order_items',COUNT(*) FROM RAW.order_items
UNION ALL SELECT 'reviews',COUNT(*) FROM RAW.reviews
ORDER BY t;
